# Use postgres/example user/password credentials
version: "3.8"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example

    webapp:
        build:
            context: https://gitlab.santis-basis.ch/christian.nuttli/hello_postgres.git
            dockerfile: ./Dockerfile
        image: hello_postgres
        restart: always
        depends_on:
            - db
        ports:
            - 8080:3000
